# -*- coding: utf-8 -*-
"""01_initial_data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sy3gkBFJMNFLV55gm2H7jT7ESm5vm0wT


[Tài liệu tham khảo Data Cleaning](https://www.kaggle.com/code/ikramshah512/amazon-products-data-cleaning-feature-engineering)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# !pip install kagglehub[pandas-datasets]

import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "amazon_products_sales_data_uncleaned.csv"

df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "ikramshah512/amazon-products-sales-dataset-42k-items-2025",
    file_path
)

"""# **Thăm dò cấu trúc dữ liệu**"""

df.head()

df.info()

df.apply(lambda col: col.astype(str).str.strip().isin([
    "", "N/A", "NA", "na", "n/a",
    "None", "none", "NULL", "null",
    "-", "--", "unknown", "Unknown"
]).sum())

df.isnull().sum()

df1 = df.copy()

num_duplicates = df1.duplicated().sum()
print(f"Số hàng bị duplicates: {num_duplicates}")

"""# Các vấn đề của bộ dữ liệu 1
1.   Sai định dạng:
  - rating: nội dung không cần thiết "out of 5 stars"
  - number_of_reviews: dấu ","
  - bought_in_last_month: nội dung, ký hiệu không cần thiết "bought in past month", "K"
  - current/discounted_price: có dấu ","
  - price_on_variant: Cột này chứa từ ngữ không cần thiết, nhiều giá trị có thông tin sai thay vì "giá", chứa các ký tự đặc biệt.
  - listed_price: chứa ký tự đặc biệt, dữ liệu không đồng nhất, cần chuẩn hóa.
  - is_couponed và buy_box_availability: cần chuẩn hóa
  - delivery_details: định dạng không nhất quán
  - product_url: Cần bổ sung thêm tên miền chính của trang web.
  2. Sai kiểu dữ liệu:
  - numeric: rating, number_of_reviews, bought_in_last_month,current/discounted_price, price_on_variant, listed_price.
  - date: delivery_details, collected_at
3. Giá trị khuyết:
  - Các cột có giá trị khuyết: rating, number_of_reviews, bought_in_last_month, current/discounted_price, buy_box_availability, delivery_details, sustainability_badges, product_url

# Làm sạch cột Rating
"""

df1['rating']

df1['rating'].isnull().sum()

df1['rating'] = df1['rating'].str.replace(r'out of 5 stars', '').str.strip().astype(float)

rating_counts = df1['rating'].value_counts(dropna=False)
print(rating_counts)

"""# Làm sạch cột number_of_reviews"""

df1['number_of_reviews']

df1['number_of_reviews'].isnull().sum()

df1['number_of_reviews'] = df1['number_of_reviews'].str.replace(',','').str.strip().astype(float)

reviews_counts = df1['number_of_reviews'].value_counts(dropna=False)
print(reviews_counts)

"""# Làm sạch cột bought_in_last_month"""

df1['bought_in_last_month']

df1['bought_in_last_month'].isnull().sum()

df1['bought_in_last_month'] = df1['bought_in_last_month'].str.replace('+ bought in past month', '').str.strip().str.replace('K', '000')
df1['bought_in_last_month'] = df1['bought_in_last_month'].where(df1['bought_in_last_month'].str.isdigit(), np.nan)
df1['bought_in_last_month'] = (df1['bought_in_last_month'].where(df1['bought_in_last_month'].str.isdigit(), np.nan).astype('Int64'))

bought_counts = df1['bought_in_last_month'].value_counts()
print(bought_counts)

df1['bought_in_last_month'].isnull().sum()

"""# Làm sạch cột price_on_variant"""

df1['price_on_variant'] = df['price_on_variant']

df1['price_on_variant'].isnull().sum()

df1['price_on_variant']

#Tách giá bằng chuỗi bằng cách chỉ lấy giá trị sau ":"
df1['price_on_variant'] = df1['price_on_variant'].str.split(':').str[1]
df1['price_on_variant'].head()

df1['price_on_variant'] = df1['price_on_variant'].str.strip()
#Chỉ giữ những dòng có ký hiệu "$", còn lại chuyển sang NaN
df1.loc[
    ~df1['price_on_variant'].str.contains(r'\$', regex=True),
    'price_on_variant'
] = np.nan

df1['price_on_variant'].head()

df1['price_on_variant'] = df1['price_on_variant'].str.split(' ').str[0]

df1['price_on_variant'].head()

df1['price_on_variant'] = (
    df1['price_on_variant']
    .str.replace(r"\$", "", regex=True)
    .str.replace(",", "")
    .astype(float)
)
df1['price_on_variant'].head()

"""# Làm sạch cột current/discounted_price"""

df1['current/discounted_price'] = df['current/discounted_price']

df1['current/discounted_price'].isnull().sum()

df1['current/discounted_price'].head()

# Xóa dấu "," và đổi kiểu dữ liệu
df1['current/discounted_price'] = df1['current/discounted_price'].str.replace(',', '').astype(float)
df1['current/discounted_price'].head()

"""# Làm sạch cột listed_price"""

df1['listed_price'] = df['listed_price']

listed_price_counts = df1['listed_price'].value_counts()
print(listed_price_counts)

df1['listed_price'] = df1['listed_price'].str.replace('$','').str.strip().str.replace(',','').str.strip()
df1['listed_price'].head()

df1['listed_price'] = df1['listed_price'].astype(str).str.strip()
df1.loc[
    df1['listed_price'] == 'No Discount',
    'listed_price'
] = df1['current/discounted_price']

df1['listed_price'] = df1['listed_price'].astype(float)

df1[['listed_price','current/discounted_price']].sample(5)

df1['listed_price'].isnull().sum()

"""# Làm sạch cột delivery_details"""

df1['delivery_details']

unique_delivery_counts = df1['delivery_details'].value_counts().unique()
print(unique_delivery_counts)

df1['delivery_details'] = df1['delivery_details'].str.extract(r'(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)?,?\s*(\w+\s+\d{1,2})')

df1['delivery_details'] = pd.to_datetime(df1['delivery_details'] + ' 2025', errors='coerce')

df1['delivery_details']

"""# Làm sạch cột Product_URL"""

#Xem giá trị của cột
df1['product_url']

# Kiểm tra chéo mục nhập đầu tiên của cột 'product_url' và 'image_url'
first_product_url = df1['product_url'].iloc[0]
first_image_url = df1['image_url'].iloc[0]

print(f"First product URL: https://www.amazon.com{first_product_url}")
print(f"First image URL: {first_image_url}")

df1['product_url'].isna().sum()

amazon_base_url = "https://www.amazon.com"
df1['product_url'] = df1['product_url'].apply(
    lambda x: amazon_base_url + x
    if pd.notna(x) and not str(x).startswith(("http://", "https://"))
    else x
)

df1['product_url'].isna().sum()

df1['product_url']

"""# Làm sạch cột Collected_At"""

df1['collected_at']

df1['collected_at'] = pd.to_datetime(df1['collected_at'])

df1.info()

